Empezamos los ejercicios depair programming con Pandas. En esta lección hemos aprendido que son las Series y DataFrames y como podemos crearlos en Python.

In [3]:
import pandas as pd
import numpy as np

Empezamos los ejercicios depair programming con Pandas. En esta lección hemos aprendido que son las Series y DataFrames y como podemos crearlos en Python.

El objetivo de la clase de hoy será crear unos cuántos dataframes y series a trvés de los siguientes ejercicios:

- ¿Qué diferencia hay entre una Serie y un Dataframe?


In [4]:
#Serie: una dimensión, que contiene un array de datos. Tiene dos componentes principales que son los indices y vector.

#DataFrame: 2 dimensiones, se pueden guardar datos de distinto tipo (string, entero, float,..),la diferencia es que hay más dimensiones y por lo tanto podemos tener mas columnas con valores.

Momento de trabajar con Series. Contestas las siguientes preguntas:

Crea dos listas:
- Una que se llame "valores" que tenga 7 números aleatorios.
- Otra que se llame "indices" que tenga 7 strings que se llamen como los dias de la semana.

A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [5]:
valores = [11,12,13,14,15,16,17]

indices = ["lunes", "martes","miercoles","jueves","viernes","sabado","domingo",]

serie1 = pd.Series(valores, index = indices)

print(serie1)

lunes        11
martes       12
miercoles    13
jueves       14
viernes      15
sabado       16
domingo      17
dtype: int64


A partir de las dos listas anteriores crea un diccionario usando un for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

In [6]:
valores = [11,12,13,14,15,16,17]
indices = ["lunes", "martes","miercoles","jueves","viernes","sabado","domingo"]

serie2 = {}

for uno,dos in zip(valores,indices): 
    serie2 [uno] = dos

#serie2 = dict((zip(valores,indices)))  # se puede hacer asi, pero con buclo FOR arriba.
print(serie2)


{11: 'lunes', 12: 'martes', 13: 'miercoles', 14: 'jueves', 15: 'viernes', 16: 'sabado', 17: 'domingo'}


Crea una Serie con el diccionario creado en el punto anterior.
- ¿Qué forma tiene esta última Serie?
- ¿Qué tipo de datos tiene?
- ¿Qué tamaño tiene?
- ¿Cuáles son los índices de la Serie?
- ¿Y los values?
- Extraed el valor para el índice "lunes"
- Extraed el valor para el índice "lunes", "martes" y "miércoles"
- Extraed el valor para el índice "lunes" y "domingo"

In [7]:
serie2 

serie3 = pd.Series(serie2)
print(serie3)

def propiedades (serie3):
    print(serie3.index) 
    print(serie3.values) 
    print(serie3.shape) #forma de la serie
    print(serie3.size) #nos devuelve nº elementos de la serie
    print(serie3.dtype) #tipo de datos

propiedades(serie3)

print(serie3.values[0])
print(serie3.values[:3])
print(serie3.values[[0,6]])


11        lunes
12       martes
13    miercoles
14       jueves
15      viernes
16       sabado
17      domingo
dtype: object
Int64Index([11, 12, 13, 14, 15, 16, 17], dtype='int64')
['lunes' 'martes' 'miercoles' 'jueves' 'viernes' 'sabado' 'domingo']
(7,)
7
object
lunes
['lunes' 'martes' 'miercoles']
['lunes' 'domingo']


Es el turno de los dataframes
- Cread un array de dos dimensiones con 4 filas y 3 columnas.
- Convertid el array en un dataframe donde las columnas se llamen "España", "Francia" e "Italia".

In [8]:
array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
df = pd.DataFrame(array)
print(array)

df = pd.DataFrame(array, columns = ["España","Francia","Italia"])
print(df)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
   España  Francia  Italia
0       1        2       3
1       4        5       6
2       7        8       9
3      10       11      12



Descargad el archivo "medallas" y cargad el dataframe con la siguiente líena de código:
    df = pd.read_csv("medallas.csv", index_col=["País"])

📌 NOTA Para evitar problemas guardar el archivo medallas.csv a la misma altura que el jupyter donde estamos trabajando.

- Usando el loc extraed todas las columnas de la fila.
- Usando el loc extraed todas las columnas de China e Irán.
- Usando el locextraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
- Usando el iloc extraed la información de la India. Devolved todas las columnas
- Usando el ilocextraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.


In [13]:
ruta = "/Users/lidiacarriedoponce/Desktop/Modulo 2 -Numpy_Pandas_/18 Abril - Pandas I/medallas.csv"
df = pd.read_csv(ruta)

print(df.loc[:]) # me lo enseña todo

print(df.loc[0,:]) # me da la info de fila 0 y todas sus columnas

print(df.loc["China" , "Irán",:]) #todas las columnas de China e Irán




   Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235
Unnamed: 0        1
País          China
Oro            1473
Plata           994
Bronce          720
Name: 0, dtype: object


IndexingError: Too many indexers

Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

Contestad a las siguientes preguntas:
- ¿Qué país consiguió más de 200 medallas de oro?
- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
- Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.
- Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.