In [1]:
import numpy as np

1. **¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?**

In [19]:
np.random.seed(1)
array = np.random.sample((3,5))
array


array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

In [20]:
np.random.seed(1)
array1 = np.random.sample((3,5))
array1
#Al plantar una semilla, podemos hacer que nuestros arrays tengan los mismos valores

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

2. **Cread los siguientes arrays:**

Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [19]:
array2 = np.random.uniform(0,10, size = (3, 2, 5))
array2 = np.round(array2)
valoresarray2 = np.unique(array2)


valoresarray2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  8.,  9., 10.])

In [23]:
array3 = np.random.binomial(10, 0.3, size = (2, 3,5))
array3

array([[[2, 1, 4, 3, 1],
        [3, 4, 2, 3, 2],
        [1, 3, 1, 5, 1]],

       [[3, 1, 5, 5, 2],
        [3, 3, 3, 6, 2],
        [2, 3, 5, 3, 3]]])

3. **En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:**

Elementos comunes entre los dos arrays

Unión de los dos arrays

¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos *⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?*


In [24]:
interseccion = np.intersect1d(array2, array3)
interseccion
#Estos son los valores únicos comunes en las 2 arrays

array([1, 2, 3, 4, 5, 6])

In [25]:
union = np.union1d(array2, array3)
union
#Une los valores de las arrays, sin que haya ningún duplicado

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
diferencia = np.setdiff1d(array2, array3)
diferencia
#Son los valores únicos que se encuentran en array2 y no están en array3

array([0, 7, 8, 9])

4. **Cread dos arrays usando el método random.rand de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.**

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.


In [28]:
arrayuno = np.random.randint(1,100, (80))
arrayuno
#Guada los conto uno por uno para verificar

array([ 7, 78, 57, 60, 16, 25, 10, 67, 72, 54, 70, 37, 22, 41, 78, 92, 50,
       48, 78, 41, 79, 46, 88, 17, 29, 46, 68, 67, 79, 47,  1, 30, 64, 76,
       36, 54, 94, 34,  3, 85, 84, 49, 55, 33, 29, 56, 83, 32, 29, 95, 75,
        9, 33,  9, 85, 78, 51, 80, 42, 65, 84, 25, 21, 45, 16, 31, 92, 15,
       20, 27, 87,  8, 54, 48, 61, 35, 33, 20, 68, 25])

In [29]:
arraydos = np.random.randint(1,100, (80))
arraydos

array([84, 95, 39, 48,  6, 80, 64, 88, 33, 43, 75, 67, 89, 99, 31, 18, 69,
       65, 61, 79, 18, 40, 36, 82, 29, 23, 39, 42, 75, 78, 71, 26, 49, 51,
       63, 45, 55,  1, 87, 17, 20, 10, 93, 52, 11, 69, 24, 15, 64, 22, 47,
        4, 57, 89, 81, 47, 55, 80, 72, 15, 78, 16, 26, 54, 85, 59, 86, 30,
       45, 38, 23, 92, 55, 77, 13, 60, 27, 77, 72, 88])

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.



In [33]:
arrayuno = np.unique(arrayuno)
arrayuno


57


In [34]:
arraydos = np.unique(arraydos)
arraydos


62



Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.



In [35]:
arraytres = np.setdiff1d(arrayuno, arraydos)
arraytres



array([ 3,  7,  8,  9, 21, 25, 32, 34, 35, 37, 41, 46, 50, 56, 68, 70, 76,
       83, 94])


Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.


In [36]:
arraycuatro = np.setdiff1d(arraydos, arrayuno)
arraycuatro



array([ 4,  6, 11, 13, 18, 23, 24, 26, 38, 39, 40, 43, 52, 59, 63, 69, 71,
       77, 81, 82, 86, 89, 93, 99])


Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.


In [37]:
arraycinco = np.intersect1d(arrayuno, arraydos)
arraycinco


array([ 1, 10, 15, 16, 17, 20, 22, 27, 29, 30, 31, 33, 36, 42, 45, 47, 48,
       49, 51, 54, 55, 57, 60, 61, 64, 65, 67, 72, 75, 78, 79, 80, 84, 85,
       87, 88, 92, 95])


¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [38]:
print(len(arrayuno))
print(len(arraydos))
print(len(arraytres))
print(len(arraycuatro))
print(len(arraycinco))
#Que tienen 2 digitos
#Que son menores de 80
#La probabilidad de que salga 100 es muy baja
#

57
62
19
24
38
