In [1]:
import numpy as np

1. Cread tres arrays: de una, dos y tres dimensiones.

Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota
- El array de 2 dimensiones debe ser de 2 filas y 3 columnas
- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [2]:
#array de 1 dimension

lista = [1,2,3]
array = np.array(lista)
print(array)

#array de 2 dimensiones 

array1 = np.random.rand(2,2,3)
print(array1)

#array multidimensional

array2 = np.random.rand(2,3,5)
print(array2)




[1 2 3]
[[[0.46870965 0.37904834 0.06615819]
  [0.44157644 0.89985209 0.78874052]]

 [[0.06457656 0.19770114 0.99180821]
  [0.08115993 0.8565591  0.65161761]]]
[[[0.54029091 0.52958611 0.37448215 0.14555468 0.4429058 ]
  [0.41663122 0.04152802 0.43736471 0.3771082  0.54480584]
  [0.84162197 0.44172664 0.96868316 0.41973111 0.85534808]]

 [[0.291088   0.55102308 0.60240295 0.06960854 0.54301208]
  [0.85031484 0.85820247 0.37404967 0.05940947 0.25659239]
  [0.20835306 0.68887776 0.21909309 0.1837065  0.62658988]]]


2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [3]:
def propiedades (array):

    print(array.shape)
    print(array.size)
    print(array.ndim)
    print(array.dtype)

propiedades(array1)


(2, 2, 3)
12
3
float64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [4]:
array3 = np.eye (3,3) #si permite mover la diagonal
print(array3)

array4 = np.identity (3) #no permite mover la diagonal
print(array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [5]:
#array2 = np.random.rand(2,3,5)
#print(array2)

array5 = np.empty_like(array2)
print(array5)

[[[0.54029091 0.52958611 0.37448215 0.14555468 0.4429058 ]
  [0.41663122 0.04152802 0.43736471 0.3771082  0.54480584]
  [0.84162197 0.44172664 0.96868316 0.41973111 0.85534808]]

 [[0.291088   0.55102308 0.60240295 0.06960854 0.54301208]
  [0.85031484 0.85820247 0.37404967 0.05940947 0.25659239]
  [0.20835306 0.68887776 0.21909309 0.1837065  0.62658988]]]


5. Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?


In [6]:
array1 = np.random.rand(2,2,3)
array4 = np.identity (3)

array6 = np.add(array1,array4)
print(array6)

# No se puede sumar por que no tienen la misma forma.


ValueError: operands could not be broadcast together with shapes (2,2,3) (3,3) 

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

In [25]:
array1 = np.random.rand(2,2,3)
print(array1)

array4 = np.ones_like(array1)
print(array4)

#suma 
suma = array1 + array4
#suma = np.add(array1,array4) 
print("Suma:",suma)

#multiplicar
multi = array1 * array4
#multiplicar = np.multiply(array1,array4) 
print("Multiplicar:", multi)

#dividir
div = array1 / array4
#dividir = np.divide(array1,array4) 
print("Dividir:", div)


[[[0.36801785 0.52564162 0.3564196 ]
  [0.13801163 0.52653105 0.3721716 ]]

 [[0.83653279 0.5903599  0.84099054]
  [0.50856668 0.62697117 0.71091764]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Suma: [[[1.36801785 1.52564162 1.3564196 ]
  [1.13801163 1.52653105 1.3721716 ]]

 [[1.83653279 1.5903599  1.84099054]
  [1.50856668 1.62697117 1.71091764]]]
Multiplicar: [[[0.36801785 0.52564162 0.3564196 ]
  [0.13801163 0.52653105 0.3721716 ]]

 [[0.83653279 0.5903599  0.84099054]
  [0.50856668 0.62697117 0.71091764]]]
Dividir: [[[0.36801785 0.52564162 0.3564196 ]
  [0.13801163 0.52653105 0.3721716 ]]

 [[0.83653279 0.5903599  0.84099054]
  [0.50856668 0.62697117 0.71091764]]]
