In [23]:
import numpy as np

1. Cread tres arrays: de una, dos y tres dimensiones.

Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota
- El array de 2 dimensiones debe ser de 2 filas y 3 columnas
- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [28]:
#array de 1 dimension

lista = [1,2,3]
array = np.array(lista)
print(array)


#array de 2 dimensiones #reapasaR!!!!!!!!!!!!!

array1 = np.random.rand(2,2,3)
print(array1)

#array multidimensional

array2 = np.random.rand(2,3,5)
print(array2)




[1 2 3]
[[[0.96225071 0.61886047 0.76278444]
  [0.69400798 0.81898302 0.61682138]]

 [[0.48470665 0.06991255 0.03218973]
  [0.07679452 0.62072883 0.82927763]]]
[[[0.78010648 0.80415893 0.37145    0.198162   0.6784933 ]
  [0.40042021 0.28964961 0.33643651 0.78714168 0.40149397]
  [0.20397419 0.75127133 0.49593789 0.37518561 0.38302372]]

 [[0.97814714 0.24764349 0.13246073 0.41533396 0.44101648]
  [0.72015852 0.62993118 0.08693379 0.27305427 0.46420225]
  [0.18001778 0.93450182 0.98184152 0.89270382 0.12449787]]]


2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [29]:
def propiedades (array):

    print(array.shape)
    print(array.size)
    print(array.ndim)
    print(array.dtype)

propiedades(array1)


(2, 2, 3)
12
3
float64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [ ]:
array3 = np.eye (3,3) #si permite mover la diagonal  DUDAAAAAAAAAAA
print(array3)

array4 = np.identity (3) #no permite mover la diagonal
print(array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [ ]:
#array2 = np.random.rand(2,3,5)
#print(array2)

array5 = np.empty_like(array2)
print(array5)

[[[0.84523075 0.76376614 0.4393994  0.11644788 0.34030121]
  [0.71692336 0.23097678 0.15752435 0.18764259 0.75822072]
  [0.94140944 0.52190927 0.91392378 0.41013368 0.09400359]]

 [[0.34992173 0.88392194 0.7263315  0.02278851 0.55251965]
  [0.51668237 0.36286662 0.5340896  0.34265317 0.40910079]
  [0.69486195 0.93990408 0.63696558 0.39099122 0.93230012]]]


5. Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?


In [ ]:
array1 = np.random.rand(2,2,3)
array4 = np.identity (3)

array6 = np.add(array1,array4)
print(array6)

#No se puede sumar por que no tienen la misma forma.


En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

In [39]:
array1 = np.random.rand(2,3,3)
print(array1)

[[[0.74560571 0.47018344 0.8371074 ]
  [0.01319916 0.28511281 0.88862141]
  [0.64094191 0.1895635  0.59131595]]

 [[0.24182037 0.96455544 0.45593767]
  [0.99261299 0.80906202 0.55967722]
  [0.70226437 0.60010053 0.37543256]]]


In [35]:
array1 = np.random.rand(2,3,3)
array4 = np.identity (2)

array6 = np.add(array1,array4)
print(array6)


[[[1.08465574 0.47191271 0.44198584]
  [0.00420891 1.38628434 0.10901005]
  [0.63088624 0.22614132 1.74556128]]

 [[1.59589823 0.03139207 0.76496073]
  [0.27837729 1.85563088 0.77758471]
  [0.27119597 0.93150883 1.84008334]]]


In [38]:
array1 = np.random.rand(2,3,3)
array4 = np.identity (3)

array6 = np.add(array1,array4)
print(array6)


[[[1.44356442 0.71605917 0.76935311]
  [0.14968389 1.51716992 0.75965623]
  [0.74883448 0.68889226 1.40475578]]

 [[1.78493205 0.45863119 0.81739059]
  [0.12637699 1.89954955 0.98375121]
  [0.57938146 0.68003298 1.88691294]]]
