In [1]:
import numpy as np

1. **¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?**

In [6]:

array = np.random.sample((3,5))
array


array([[0.67046751, 0.4173048 , 0.55868983, 0.14038694, 0.19810149],
       [0.80074457, 0.96826158, 0.31342418, 0.69232262, 0.87638915],
       [0.89460666, 0.08504421, 0.03905478, 0.16983042, 0.8781425 ]])

In [8]:
# np.random.seed(1)
array1 = np.random.sample((3,5))
array1
#Al plantar una semilla, podemos hacer que nuestros arrays tengan los mismos valores

array([[0.67046751, 0.4173048 , 0.55868983, 0.14038694, 0.19810149],
       [0.80074457, 0.96826158, 0.31342418, 0.69232262, 0.87638915],
       [0.89460666, 0.08504421, 0.03905478, 0.16983042, 0.8781425 ]])

2. **Cread los siguientes arrays:**

Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

In [19]:
array2 = np.random.uniform(0,10, size = (3, 2, 5))
array2 = np.round(array2)
valoresarray2 = np.unique(array2)


valoresarray2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  8.,  9., 10.])

In [23]:
array3 = np.random.binomial(10, 0.3, size = (2, 3,5))
array3

array([[[5, 3, 4, 3, 4],
        [3, 4, 3, 3, 2],
        [1, 2, 1, 6, 2]],

       [[4, 5, 4, 3, 2],
        [3, 2, 2, 3, 2],
        [5, 5, 2, 1, 2]]])

3. **En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:**

Elementos comunes entre los dos arrays

Unión de los dos arrays

¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos *⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?*


4. **Cread dos arrays usando el método random.rand de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.**

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.
